// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sscwghkkggsqpwbxlplm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzY3dnaGtrZ2dzcXB3YnhscGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTQxODUsImV4cCI6MjA2ODI5MDE4NX0.eOjA2cVzvM_Y6He8FyLKnSqROkf7evm0v_H78jeeI7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});